import { SxProps } from "@mui/material";
import { colors, fonts, hex2rgba } from "../../../../config/theme";

export const bannerSectionStyles = {
  backgroundImageStyles: {
    width: "100%",
    aspectRatio: "21/9",
    objectFit: "cover",
    position: "relative",
    height: { xs: "80dvh", sm: "904px" },
  },
  logoImg: {
    width: { xs: "50px", sm: "85px" },
  },
  container: {
    padding: { xs: "35px", lg: "35px 105px" },
    position: "absolute",
    top: "10px",
    left: "8px",
    right: "1px",
    bottom: "50px",
  },

  logoContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: { xs: "20px", md: "0px" },
  },
  loginBtnStyle: {
    boxShadow: `2px 2px 12px 0px ${hex2rgba(colors.black, 0.2)}`,
    color: colors.white,
    borderRadius: "10px",
    background: colors.labelText,
    fontSize: "clamp(1rem, 0.9846rem + 0.0877vw, 1.125rem)",
    textTransform: "capitalize",
    padding: { xs: "8px 10px", sm: "26px 55px" },
    marginRight: "10px",
    fontFamily: fonts.third,
    fontWeight: "700",
  },
  registerBtnStyle: {
    boxShadow: `2px 2px 12px 0px ${hex2rgba(colors.black, 0.2)}`,
    color: colors.white,
    borderRadius: "10px",
    background: colors.activeColor,
    fontSize: "clamp(1rem, 0.9846rem + 0.0877vw, 1.125rem)",
    textTransform: "capitalize",
    padding: { xs: "8px 10px", sm: "26px 55px" },
    marginRight: "10px",
    fontFamily: fonts.third,
    fontWeight: "700",
  },
  btnContainer: {
    display: "flex",
    flexWrap: "wrap",
  },
  landingPageTextConatiner: {
    display: "flex",
    flexDirection: "column",
    flex: 0.5,
    alignItems: "flex-start",
    gap: 2,
    marginTop: { xs: "50px", sm: "230px" },
  },
  welcomeTextContainer: {
    background: colors.white,
    borderRadius: "10px",
    boxShadow: `2px 2px 12px 0px ${hex2rgba(colors.black, 0.2)}`,
    padding: "12px 25px",
    color: colors.black,
    fontSize: "clamp(1rem, 0.9846rem + 0.0877vw, 1.125rem)",
    fontWeight: "600",
    fontFamily: fonts.third,
  },
  spanText: {
    color: colors.activeColor,
  },
  title: {
    fontSize: "clamp(1.875rem, 1.8366rem + 0.2193vw, 2.1875rem)",
    fontWeight: "900",
    lineHeight: "42px",
    color: colors.gunMetal,
    fontFamily: fonts.third,
  },
  dividerStyle: {
    backgroundColor: colors.yellow,
    height: "5px",
    fontSize: "clamp(1rem, 0.9846rem + 0.0877vw, 1.125rem)",
    width: "65px",
    borderRadius: "10px",
    borderBottomWidth:"inherit"
  },
  description: {
    fontSize: "clamp(0.75rem, 0.727rem + 0.1316vw, 0.9375rem)",
    fontWeight: "500",
  },
  btnStyle: {
    color: hex2rgba(colors.black, 0.9),
    background: colors.yellow,
    borderRadius: "10px",
    fontSize: "clamp(1rem, 0.9846rem + 0.0877vw, 1.125rem)",
    fontWeight: "700",
    padding: "12px 25px",
    "&:hover": {
      background: colors.yellow,
      color: hex2rgba(colors.black, 0.9),
    },
    fontFamily: fonts.third,
    cursor: "pointer",
  },
  formText: {
    width: "100%",
    textAlign: "center",
    display: "inline",
    alignItems: "center",
    justifyContent: "center",
    mt: 2.5,
    color: colors.white,
  },
  signInUpText: {
    color: colors.darkBlue,
    cursor: "pointer",
    fontSize: "16px",
  },
  modalStyle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    maxHeight: "90vh",
    maxWidth: "100%",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    boxSizing: "border-box",
    borderRadius: "30px",
    p: 4,
    bgcolor: colors.lightBlack,
    boxShadow: "rgba(226, 236, 249, 0.5) 0px 10px 60px 0px",
  },
  modalBox: {
    display: "flex",
    flexDirection: "column",
    bgcolor: colors.lightBlack,
    maxHeight: "81vh",
    overflow: "auto",
    mt: 2,
    "::-webkit-scrollbar": {
      display: "none",
    },
  },
} satisfies Record<string, SxProps>;
