 export const baseURL = "http://122.175.39.120:8087/dadz-api";
// export const baseURL = "http://192.168.1.12:8087/dadz-api";
export const endpoints = {
  SENT_OTP: "user/sendOtp",
  SEND_OTP_EMAIL_OR_MOBILE: "user/sendOtp/emailMobile",
  VERIFY_OTP: "user/verifyOtp/emailMobile",
  SIGNUP_VERIFY_OTP: "user/verifyOtp",
  UPDATE_PASSWORD: "user/forgotpassword",
  SIGN_UP: "user",
  SIGN_IN: "user/emaillogin",
  ROLES: "roles",
  GET_AGREEMENT_DOCUMENT: "agreementdocument",
  GET_PRIVACY_POLICY: "privacypolicy",
  GET_ABOUT_US: "aboutus",
  GET_TERMS_AND_CONDITIONS: "termsandconditions",
  PLAYLIST: "playlist",
  SCREEN_SCREENMEDIA: "screen/pendingmedia",
  SCREEN: "screen",
  SCREEN_SELECT: "screen/select",
  SCREEN_SAVE_GROUP: "screen/savegroup",
  SCREEN_IMAGE: "screen/files",
  SCREENGROUP: "screengroup",
  GET_VENDOR_QR_CODES: "qr/getAllQRCodes",
  GET_PLAYLISTS: "playlist?",
  DELETE_PLAYLIST: "playlist",
  DELETE_SCREEN: "screen",
  GROUP: "group",
  POST_COMMISSIONS: "commissions",
  GET_COMMISSIONS: "commissions",
  AD_AGENCY_ADS: "playlist",
  MEDIA: "media",
  GET_PENDING_REQUEST: "user/all",
  UPDATE_USER_ACTION: "user",
  GET_CAMPAIGN_REQUEST: "campaign",
  UPDATE_CAMPAIGN_ACTION: "campaign/status",
  USER_LOGS: "user/logs",
  EXPORT_USER_LOGS: "user/exportLogs",
  GET_GENRES: "genre",
  GET_CATEGORIES: "category",
  GET_SUB_CATEGORIES: "subcategory",
  GET_SCREEN_GROUPS: "screengroup",
  GET_SCREENS: "screen",
  GET_COUPONS: "coupon",
  GET_USERS_Accepted: "user/all",
  USER_UPDATE: "user",
  GROUP_MEMBER: "groupmember",
  SUPER_ADMIN_REPORTS_DASHBOARD: "dashboard/superadmin_report",
  SUPER_ADMIN_DASHBOARD: "dashboard/superadmin",
  ADMIN_DASHBOARD: "dashboard/admin",
  CREAT_NEW_SCREEN: "screen",
  UPDATE_PLAYLISTDATA: "playlist",
  PAYMENTS_DATA: "campaign/payments",
  CAMPAIGN: "campaign",
  PRICING_MODEL: "pricingmodel",
  AD_TYPE: "adtype",
  MEMBER_PERMISSION: "user/permission",
  GET_SCREEN_FILES: "screen/files",
  VENDOR_SCANS: "dashboard/vendorScans",
  VENDOR_STATS: "dashboard/vendorStats",
  GET_GROUPS: "screen/avalibility",
  APPLY_COUPON: "campaign/apply-coupon",
  REMOVE_COUPON: "campaign/remove-coupon",
  CHECKOUT: "campaign/checkout",
  PAYMENT: "campaign/payment",
  CALLBACK: "campaign/callback",
  GET_ADDITIONAL_INFO: "screenadditionalinformation/screen/",
  GET_ORDER_ID: "wallet/add-money",
  POST_PAYMENT_ID: "wallet/confirm-payment",
  GET_WALLET_DETAILS: "wallet/details",
  GET_WALLET_TRANSACTIONS: "wallet/transactions",
  USER_DASHBOARD: "dashboard/user",
  WIDGET: "widget",
  SUB_WIDGET: "widget/subwidget",
  WIDGET_SUB_WIDGET: "widget/subwidgets",
  DELETE_SUB_WIDGET: "widget/subwidget",
  REMOVE_SCREEN_FROM_GROUP: "screen/removegroup",
  GET_SCREENS_WITH_EXISTING: "screen/byscreengroups",
  SCREEN_UPTIME: "screen/uptime",
  INVESTOR_DASHBOARD: "dashboard/investor",
  HOST_DASHBOARD: "dashboard/host",
  MY_SCREEN_LOCATIONS: "screen/mylocations",
  SUPER_ADMIN_SALES_DETAILS: "dashboard/superadminreport",
  SCREEN_PRICING: "screenpricing",
  GET_TEAM_GROUPS: "group",
  GET_GROUP_MEMBERS: "groupmember",
  CAMPAIGN_ASSIGN: "campaign/assign",
  GET_PENDING_MEDIA: "screen/pendingmedia",
  GET_CAMPAIGN_DETAILS: "campaign/get/",
  GET_HOST_SCREENS: "screen/hostscreens",
  UPDATE_HOST_AD_REQUEST: "screen/mediastatus/",
  POST_MEDIA_HOST: "screen/screenmedia",
  POST_PLAYLIST_ADS:"playlist/assign/ads",
  GET_PLAYLIST_ADS:"playlist/ads?playlistId=",
  PLAYLIST_ADS: "playlist/ads",
  GET_PLAYLIST_SCHEDULE: "playlist/adschedule",
  PLAYLIST_SCHEDULE: "playlist/playlistad",
  PLAYLIST_SAVE_SCREENS: "playlist/savescreentoad",
  PLAYLIST_SAVE_GROUPS: "playlist/savescreengroupstoad",
  REMOVE_SCREEN_FROM_AD: "playlist/removescreentoad",
  REMOVE_GROUP_FROM_AD: "playlist/removescreengrouptoad",
  CAMPAIGN_STATUS_CHANGE_BY_TEAM_MEMBER:"campaign/campaignstatusbyteammember"
};
export const encryptionSalt = "4910474157405c535f5710081053565f";

export const roles = {
  ADMIN: 7,
  USER: 9,
  SUPER_ADMIN: 6,
  AD_AGENCY: 12,
  HOST: 8,
  VENDERS: 10,
  INVESTORS: 11,
};
